infiniteopt/InfiniteOpt.jl

appveyor.yml, docs/src/guide/constraint.md, src/InfiniteOpt.jl, src/constraints.jl, src/macros.jl, src/show.jl, src/utilities.jl, test/constraints.jl, test/parameters.jl, test/runtests.jl, test/show.jl, test/utility_tests.jl
Fully enable bounded constraint definition via a macro interface. Also, enable point constraints via bounded constraint syntax.
=> Bounded constraints

docs/src/guide/parameter.md, src/InfiniteOpt.jl, src/macros.jl, src/measures.jl, src/parameters.jl, test/TranscriptionOpt/transcribe.jl, test/constraints.jl, test/measures.jl, test/parameters.jl, test/variable_definition.jl
Some minor support fixes and added functionality to define finite parameters
=> Finite parameters

docs/make.jl, docs/src/guide/measure.md, docs/src/guide/model.md, docs/src/guide/transcribe.md, src/datatypes.jl
=> Measure documentation page

docs/src/examples.md
Added distillation example to docs
=> Distillation Example Update

README.md, docs/src/index.md
Final preparations/updates for new major release of v0.2.0
=> v0.2.0 prep

src/Collections/VectorTuple.jl, src/datatypes.jl, test/Collections/VectorTuple.jl, test/datatypes.jl
Fixes 32-bit errors related to using `CleverDicts`.
=> Fix 32bit Support

docs/src/JuMP.md
=> Added Documentation to JuMP.md

docs/src/develop.md, docs/src/guide/derivative.md, docs/src/guide/install.md, docs/src/guide/measure.md, docs/src/guide/model.md, docs/src/guide/parameter.md, docs/src/guide/sets.md, docs/src/guide/variable.md, src/InfiniteOpt.jl, src/MeasureToolbox/integrals.jl, src/array_parameters.jl, src/datatypes.jl, src/derivative_evaluations.jl, src/infinite_sets.jl, src/measures.jl, src/results.jl, src/scalar_parameters.jl, src/show.jl, test/array_parameters.jl, test/datatypes.jl, test/derivative_evaluation.jl, test/infinite_sets.jl, test/measure_expansions.jl, test/measures.jl, test/results.jl, test/runtests.jl, test/scalar_parameters.jl, test/show.jl
This comprises some minor fixes to derivative support. This also closes #72.
=> Derivative Implementation Fixes

docs/make.jl, docs/src/extensions.md, docs/src/guide/optimize.md, docs/src/guide/result.md, docs/src/guide/transcribe.md, src/TranscriptionOpt/model.jl, src/array_parameters.jl, src/constraints.jl, src/derivative_evaluations.jl, src/derivatives.jl, src/general_variables.jl, src/infinite_variables.jl, src/macros.jl, src/optimize.jl, src/reduced_variables.jl, src/results.jl, src/scalar_parameters.jl, test/TranscriptionOpt/model.jl, test/extensions/optimizer_model.jl, test/optimizer.jl, test/results.jl
This implements what was proposed in #73. There is room for improvement in the future, but this adds the basic functionality.
=> N-Dimensional Array Queries

README.md
=> v0.3.0 prep

CONTRIBUTING.md, docs/src/develop.md, docs/src/examples.md, docs/src/extensions.md
**Summary**
I found a few typos while reading the docs and the contributing page for the package.
This PR fixes/implements the following **bugs/features**
**Closing issues**
N/A.
=> Fix miscellaneous typos

docs/src/JuMP.md, docs/src/extensions.md, docs/src/guide/measure.md, docs/src/guide/model.md, docs/src/guide/result.md, src/InfiniteOpt.jl, src/constraints.jl, src/datatypes.jl, src/general_variables.jl, src/results.jl, test/constraints.jl, test/datatypes.jl, test/general_variables.jl, test/results.jl
=> Update with JuMP 0.21.6

.travis.yml, README.md, appveyor.yml, docs/src/guide/install.md, docs/src/index.md, test/Collections/DualDict.jl, test/measure_expansions.jl, test/show.jl, test/utilities.jl
Update testing and docs for Julia v1.6
=> Update to Julia 1.6

docs/src/extensions.md, docs/src/guide/expression.md, docs/src/guide/measure.md, src/MeasureToolbox/integrals.jl, test/MeasureToolbox/integrals.jl
Cleans up our integral implementation and fixes a few errors. Closes #120.
=> Integral fixes

docs/src/extensions.md, docs/src/guide/measure.md, src/MeasureToolbox/MeasureToolbox.jl, src/MeasureToolbox/expectations.jl, src/MeasureToolbox/integrals.jl, src/MeasureToolbox/support_sums.jl, test/MeasureToolbox/expectations.jl, test/MeasureToolbox/integrals.jl, test/MeasureToolbox/support_sums.jl, test/extensions.jl, test/extensions/infinite_domain.jl, test/show.jl
=> Overhaul of expect and support_sum

.github/workflows/CompatHelper.yml, docs/Project.toml
Update to Documenter `v0.27` and make CompatHelper start checking the doc versioning.
=> Update Documentation Versioning

docs/src/guide/constraint.md, docs/src/guide/variable.md, docs/src/manual/variable.md, src/general_variables.jl, src/infinite_variables.jl, src/point_variables.jl, src/semi_infinite_variables.jl, test/derivatives.jl, test/general_variables.jl, test/infinite_variables.jl, test/point_variables.jl, test/scalar_parameters.jl, test/semi_infinite_variables.jl, test/utilities.jl
=> Added variable restrictions

.github/workflows/ci.yml, .github/workflows/docs.yml
These changes will ensure that workflows don't run on draft pull requests.
=> Update Workflows for Drafts

docs/src/develop/extensions.md, docs/src/develop/style.md, docs/src/guide/constraint.md, docs/src/guide/derivative.md, docs/src/guide/domains.md, docs/src/guide/expression.md, docs/src/guide/finite_parameter.md, docs/src/guide/measure.md, docs/src/guide/model.md, docs/src/guide/objective.md, docs/src/guide/optimize.md, docs/src/guide/parameter.md, docs/src/guide/result.md, docs/src/guide/transcribe.md, docs/src/guide/variable.md, docs/src/index.md, docs/src/install.md, docs/src/manual/constraint.md, docs/src/manual/variable.md, docs/src/tutorials/quick_start.md
This updates our links for JuMP `v1.0` it also resolves a few existing bugs and updates some language.
=> Update Docs for JuMP v1

docs/src/guide/derivative.md, docs/src/guide/variable.md, src/derivatives.jl, test/derivatives.jl
=> Fix Derivative Update Bug

docs/src/examples/Stochastic Optimization/farmer.jl, docs/src/examples/Stochastic Optimization/flexible_design.jl
This cleans ups the stochastic programming examples and clarifies the that the results will change depending on the random scenarios. Closes #269.
Example preview: https://pulsipher.github.io/InfiniteOpt.jl/previews/PR270/examples/Stochastic%20Optimization/farmer/
=> Clarify Generation of Random Scenarios in SO Examples

src/MeasureToolbox/integrals.jl, src/datatypes.jl, test/MeasureToolbox/integrals.jl, test/datatypes.jl
=> Fix Generative Supports for Empty Sets

src/TranscriptionOpt/transcribe.jl, test/TranscriptionOpt/transcribe.jl
=> Fix Transcription w/ Constrained Nonlinear Measures

test/optimizer_setup.jl
This PR fixes the error type that is changing in MOI v1.23: https://github.com/jump-dev/MathOptInterface.jl/pull/2353
=> Fix test for MOI v1.23.0

docs/src/develop/extensions.md, docs/src/guide/derivative.md, docs/src/manual/derivative.md, src/InfiniteOpt.jl, src/derivative_evaluations.jl, test/derivative_evaluation.jl, test/extensions/derivative_method.jl
This makes the derivative evaluation API more modular. It is greatly helpful for InfiniteExaModels to not duplicate the reformulation code and also increases performance.
=> Improve the Extensibility of Derivative Methods
