infiniteopt/InfiniteOpt.jl

docs/src/examples.md, docs/src/extensions.md, docs/src/guide/constraint.md, docs/src/guide/derivative.md, docs/src/guide/measure.md, docs/src/guide/objective.md, docs/src/quick_start.md, src/InfiniteOpt.jl, src/MeasureToolbox/expectations.jl, src/MeasureToolbox/integrals.jl, src/derivatives.jl, src/measures.jl, src/show.jl, src/variable_basics.jl, test/MeasureToolbox/expectations.jl, test/MeasureToolbox/integrals.jl, test/derivatives.jl, test/show.jl
Added `∂`, `∫`, and `𝔼` as wrappers for `deriv`, `integral`, and `expect`, respectively. Wrappers for the more efficient macro variants were also added.
=> Symbolic wrappers

docs/src/guide/measure.md, src/InfiniteOpt.jl, src/MeasureToolbox/integrals.jl, test/MeasureToolbox/integrals.jl, test/extensions.jl
Added the following Quadrature Methods:
Gauss-Lobatto
Gauss-Radau
Gauss-Jacobi
In addition I changed the syntax of the eval methods in integrals.jl. Previously one would choose Gauss Legendre quadrature by doing eval_method = GaussRadau, however it is now eval_method = GaussRadau()). This is to allow for parameters to get passed to quadrature methods that require additional inputs such as Gauss Jacobi. I also updated all the documentation to reflect this.
=> Added Quadrature Methods for Integration

Project.toml, docs/src/guide/expression.md, src/InfiniteOpt.jl, src/datatypes.jl, src/expressions.jl, src/infinite_variables.jl, src/macro_utilities.jl, src/macros.jl, src/utilities.jl, test/datatypes.jl, test/expressions.jl, test/infinite_variables.jl, test/macro_utilities.jl, test/point_variables.jl, test/utility_tests.jl
Closes #115 and #93.
This also partially addresses #60 in removing all the internal JuMP functions except for `JuMP.Containers._build_ref_sets`.
=> Much Enhanced Parameter Functions

Project.toml, docs/src/examples.md, docs/src/extensions.md, docs/src/guide/constraint.md, docs/src/guide/derivative.md, docs/src/guide/expression.md, docs/src/guide/finite_parameter.md, docs/src/guide/install.md, docs/src/guide/measure.md, docs/src/guide/model.md, docs/src/guide/objective.md, docs/src/guide/optimize.md, docs/src/guide/parameter.md, docs/src/guide/result.md, docs/src/guide/sets.md, docs/src/guide/transcribe.md, docs/src/guide/variable.md, docs/src/quick_start.md, examples/3node_flexible_design.jl, examples/hovercraft.jl, src/InfiniteOpt.jl, src/MeasureToolbox/MeasureToolbox.jl
Closes #103 and cleans up the exporting structure of InfiniteOpt using `Rexport.@reexport`.
=> Revamped Exporting Configuration

docs/src/examples/Optimal Control/consumption_savings.jl
Adds a simple/routine economics example. Discussed in issue https://github.com/pulsipher/InfiniteOpt.jl/issues/131.
=> Create example consumption_savings.jl

src/macros.jl, test/expressions.jl
Fixed erroneous naming for anonymous parameter functions that use anonymous functions. Moreover, added functionality to allow anonymous functions defined with indexed parameter inputs, for instance:
```julia
@parameter_function(model, pfunc[i = 1:2] == (t, x[i]) -> t + x[i])
```
=> Parameter Function Bug Fix

.github/workflows/docs.yml, docs/Project.toml
This uses the new version of Ipopt to resolve the issues described here: https://discourse.julialang.org/t/link-checking-with-github-actions-not-working/61823.
=> Resolve Linkcheck Problems with Ipopt

docs/src/guide/model.md, docs/src/index.md, src/TranscriptionOpt/transcribe.jl, src/optimize.jl, test/TranscriptionOpt/transcribe.jl, test/optimizer.jl
Before the support check at transcription errored with finite models:
```julia
m = InfiniteModel()
@variable(m, y >= 0)
build_optimizer_model!(m)
```
```julia
ERROR: ArgumentError: reducing over an empty collection is not allowed
Stacktrace:
[1] _empty_reduce_error()
@ Base .\reduce.jl:299
[2] mapreduce_empty(f::Function, op::Base.BottomRF{typeof(Base.mul_prod)}, T::Type)
@ Base .\reduce.jl:342
[3] reduce_empty(op::Base.MappingRF{typeof(length), Base.BottomRF{typeof(Base.mul_prod)}}, #unused#::Type{Union{}})
@ Base .\reduce.jl:329
[4] reduce_empty_iter
@ .\reduce.jl:355 [inlined]
[5] reduce_empty_iter
@ .\reduce.jl:354 [inlined]
[6] foldl_impl(op::Base.MappingRF{typeof(length), Base.BottomRF{typeof(Base.mul_prod)}}, nt::Base._InitialValue, itr::Tuple{})
@ Base .\reduce.jl:49
[7] …
```
=> Discourage Finite Models

Project.toml, src/InfiniteOpt.jl, src/TranscriptionOpt/TranscriptionOpt.jl, test/utilities.jl
This is a test to see if we can remove MOI.
**EDIT:** 
It appears that we can since `Reexport` exports the `MOI` alias defined in `JuMP`.
=> Remove MOI as Explicit Dependency

Project.toml, docs/src/develop/start_guide.md, docs/src/install.md, test/nlp.jl
This follows up from #182 to now require 1.6 and drop support for all previous versions.
=> Require at Least Julia 1.6

docs/src/develop/extensions.md, src/MeasureToolbox/expectations.jl, test/MeasureToolbox/expectations.jl
This fixes a bug that `𝔼` didn't accept the `pdf` keyword
=> Minor Keyword Argument Fix with 𝔼

docs/src/guide/expression.md, src/nlp.jl, test/array_parameters.jl, test/deletion.jl, test/expressions.jl, test/macro_expressions.jl, test/nlp.jl
This follows from https://github.com/jump-dev/JuMP.jl/pull/2842.
Until JuMP.jl releases this bug fix in the next version, we can use the work around:
```julia
using InfiniteOpt
model = InfiniteModel()
@variable(model, z)
my_max(a...) = max(a...)
@register(model, my_max(a, b))
@objective(model, Min, my_max(0, z))
```
Once, JuMP.jl is updated then we can just register as normal:
```julia
using InfiniteOpt
model = InfiniteModel()
@variable(model, z)
@register(model, max(a, b))
@objective(model, Min, max(0, z))
```
=> Remove `max` and `min` as default NLP functions

test/TranscriptionOpt/model.jl, test/TranscriptionOpt/transcribe.jl
This follows from https://github.com/jump-dev/JuMP.jl/pull/2893.
=> Drop Use of `nl_` String Functions

docs/src/develop/start_guide.md, docs/src/guide/variable.md, src/nlp.jl, test/nlp.jl
Closes #260. 
@FedeClaudi, I think this should fix your problems. Can you please check it with your use case. You can checkout this branch via:
```julia
julia> ]
pkg> add InfiniteOpt#prod_patch
```
If it works, then I will merge this and release a new version of InfiniteOpt.
=> Fix Generality of `sum` and `prod`

docs/src/develop/extensions.md
This simplifies the the documentation for defining optimizer models, eliminating most internal functions from the tutorial (we are just left with `InfiniteOpt._model_from_expr`). 
We probably will need to add a few public functions to prevent this completely, this should be considered in #248.
=> Simplify Optimizer Model Docs

docs/src/manual/constraint.md, src/constraints.jl
Fixes the issue discussed in https://github.com/jump-dev/JuMP.jl/issues/3330. It appears we can just enforce `set::MOI.AbstractSet` to fix the problem.
I also removed some unnecessary type checks when I was at it.
=> Fix Ambiguity with JuMP 1.10

docs/jump/README.md
This addresses the concerns of @odow raised in #311. 
@odow: Any other concerns or suggestions?
=> Finalize JuMP README

docs/src/guide/expression.md, src/nlp.jl
We swapped the order of arguments to `NonlinearOperator`. Otherwise, tests as passing with https://github.com/jump-dev/JuMP.jl/pull/3489
=> Update for NonlinearOperator change

src/expressions.jl, test/expressions.jl
This fixes a bug when building ASTs to avoid the case where we get `:(+())` which is not valid Julia code.
=> Prevent empty `+()` when mapping to ASTs

docs/src/examples/Optimal Control/pandemic_control.jl, docs/src/guide/derivative.md, docs/src/guide/measure.md, docs/src/manual/expression.md, docs/src/manual/transcribe.md, docs/src/manual/variable.md, docs/src/tutorials/quick_start.md, src/TranscriptionOpt/model.jl, src/TranscriptionOpt/transcribe.jl, src/datatypes.jl, src/derivative_evaluations.jl, src/general_variables.jl, src/infinite_variables.jl, test/TranscriptionOpt/transcribe.jl, test/deletion.jl, test/general_variables.jl, test/infinite_variables.jl
To resolve the degrees of freedom encountered by control variables with orthogonal collocation, this introduces `constant_over_collocation` to have control variables held to one a single degree of freedom per finite element. Closes #216.
=> Implement `constant_over_collocation`

src/macros.jl, test/expressions.jl, test/scalar_parameters.jl
This fixes a few bugs related to handling macros with the syntax `@myobject(model, expr; kwargs...)`.
=> Fix keyword parsing with `;` in macros

src/MeasureToolbox/integrals.jl, test/MeasureToolbox/integrals.jl
=> Fix Gauss Chebyshev Deprecation Error

docs/src/manual/model.md, src/TranscriptionOpt/optimize.jl, src/datatypes.jl, src/optimize.jl, test/datatypes.jl, test/optimizer.jl
This adds the necessary changes to make InfiniteOpt compatible with DisjunctiveProgramming.
=> Add `set_optimize_hook`

docs/src/develop/extensions.md, docs/src/guide/constraint.md, docs/src/guide/derivative.md, docs/src/manual/domains.md, src/array_parameters.jl, src/infinite_domains.jl, src/scalar_parameters.jl, test/array_parameters.jl, test/extensions/infinite_domain.jl, test/scalar_parameters.jl
If domains are specified with more sigfigs than are used for the supports, then an out of bounds error will likely result. To fix this, domains are now rounded to the same amount of sigfigs as well. See https://discourse.julialang.org/t/infiniteopt-supports-violate-the-domain-bounds/115751.
=> Fix SigFig Bug

docs/src/manual/expression.md, src/expressions.jl, test/expressions.jl
=> Support Expression Restrictions

docs/src/examples/Optimal Control/pandemic_control.jl, docs/src/guide/measure.md, docs/src/guide/optimize.md, docs/src/guide/result.md, docs/src/guide/transcribe.md, docs/src/manual/transcribe.md, src/TranscriptionOpt/model.jl, src/TranscriptionOpt/transcribe.jl, src/backends.jl, src/results.jl, src/semi_infinite_variables.jl, test/TranscriptionOpt/measure.jl, test/TranscriptionOpt/model.jl, test/TranscriptionOpt/transcribe.jl, test/backend_mappings.jl, test/results.jl
This PR removes `ndarray` as a keyword argument and essentially makes `ndarray = true` the default behavior. Users that still prefer to get a vector output can simply use `vec` to vectorize.
This PR simplifies the way TranscriptionOpt reports back mappings, improves printing for transcribed variables, and enhances the robustness/efficiency of making n-dimensional arrays for transcribed mappings.
=> Remove `ndarray` Keyword Argument

docs/src/guide/parameter.md, src/array_parameters.jl, src/datatypes.jl, test/TranscriptionOpt/model.jl, test/TranscriptionOpt/transcribe.jl, test/array_parameters.jl, test/datatypes.jl
The use of `Dict` for multi-dimensional dependent infinite parameter supports leads to stochastic ordering of supports. This is problematic when the user queries the results, since the ordering cannot be known a priori. Hence, this PR simply replaces `Dict` with `DataStructures.OrderedDict`.
=> Use `OrderedDict` for Array Parameter Supports

src/TranscriptionOpt/measures.jl, src/TranscriptionOpt/transcribe.jl, test/TranscriptionOpt/measure.jl, test/TranscriptionOpt/transcribe.jl
#356 added a lot of unneeded operations for semi-infinite variables that are generated internally during transcription. This removes the unnecessary operations and allocations.
=> Improve Performance of Internal Semi-Infinite Variables

src/Collections/VectorTuple.jl, test/Collections/VectorTuple.jl
A previously unnoticed is bug occurred with the following:
```julia
julia> vt = VectorTuple([1, 2])
([1, 2],)
julia> InfiniteOpt.Collections.restricted_copy(vt, [true, false])
ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type InfiniteOpt.Collections.ContainerIndices{1, Nothing}
Closest candidates are:
convert(::Type{T}, ::T) where T
@ Base Base.jl:64
(::Type{InfiniteOpt.Collections.ContainerIndices{N, Ax}} where {N, Ax})(::Any, ::Any)
@ InfiniteOpt C~\InfiniteOpt.jl\src\Collections\vectorize.jl:11
Stacktrace:
[1] setindex!(A::Vector{InfiniteOpt.Collections.ContainerIndices{1, Nothing}}, x::Nothing, i1::Int64)
@ Base .\array.jl:969
[2] restricted_copy(vt::VectorTuple{Int64, Tuple{InfiniteOpt.Collections.ContainerIndices{1, Nothing}}}, inds::Vector{Bool})
@ …
```
=> Fix bug in `restricted_copy`

src/general_variables.jl, test/general_variables.jl
This is needed for the DisjunctiveProgramming extension which checks every term in an expression with `JuMP.is_binary`.
=> Improve Defaults of `JuMP.is_binary`, `JuMP.is_integer`, and `JuMP.is_fixed`

docs/src/examples/Optimal Control/Fishing.jl, docs/src/examples/Optimal Control/Hanging Chain.jl, docs/src/examples/Optimal Control/Jennings.jl
Three new problems added:
Hanging Chain
Jennings
Fishing
=> Addition of three new examples under optimial control.

docs/src/guide/transcribe.md, docs/src/manual/transcribe.md, src/TranscriptionOpt/model.jl, src/TranscriptionOpt/transcribe.jl, test/TranscriptionOpt/model.jl, test/TranscriptionOpt/transcribe.jl
Currently, finite parameters are transcribed as scalar values and can only be updated by remaking the JuMP backend from scratch. This PR makes it easier to update finite parameter values by transcribing them as `JuMP.Parameter`s instead, avoiding the need to remake the JuMP backend.
=> Map finite parameters to JuMP.Parameters
